import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './navbar.js';
import Footer from './footer.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className + ' flex flex-col min-h-screen px-5 md:px-20 pt-8 md:pt-14 pb-6 md:pb-10'}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
